# Generated by Django 5.0.6 on 2024-10-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0008_alter_comment_options_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='parent_post',
            new_name='parent_comment',
        ),
    ]
